[theme]
base = "light"
primaryColor = "#176BDA"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#10233D"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
